language: php
php:
  - 5.6
  - 7.0

install:
  - composer install  --no-interaction --prefer-dist

cache:
  directories:
  - $HOME/.composer/cache/repo/
  - $TRAVIS_BUILD_DIR/vendor/

script:
  - composer validate
  - ./vendor/bin/phpunit
  - ./vendor/bin/php-cs-fixer fix . --dry-run -v --level=psr2

branches:
  only:
    - master

notifications:
  email:
    on_success: never
